package model;
// Generated 10/04/2016 05:15:29 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Galeria generated by hbm2java
 */
@Entity
@Table(name="galeria"
    ,schema="public"
)
public class Galeria  implements java.io.Serializable {


     private int idfoto;
     private Publicacion publicacion;
     private String foto;

    public Galeria() {
    }

	
    public Galeria(int idfoto, Publicacion publicacion) {
        this.idfoto = idfoto;
        this.publicacion = publicacion;
    }
    public Galeria(int idfoto, Publicacion publicacion, String foto) {
       this.idfoto = idfoto;
       this.publicacion = publicacion;
       this.foto = foto;
    }
   
     @Id 

    
    @Column(name="idfoto", unique=true, nullable=false)
    public int getIdfoto() {
        return this.idfoto;
    }
    
    public void setIdfoto(int idfoto) {
        this.idfoto = idfoto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpublicacion", nullable=false)
    public Publicacion getPublicacion() {
        return this.publicacion;
    }
    
    public void setPublicacion(Publicacion publicacion) {
        this.publicacion = publicacion;
    }

    
    @Column(name="foto")
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


