package model;
// Generated 10/04/2016 05:15:29 AM by Hibernate Tools 4.3.1

import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Publicacion generated by hbm2java
 */
@Entity
@Table(name = "publicacion", schema = "public"
)
public class Publicacion implements java.io.Serializable {

    private int idpublicacion;
    private Usuario usuarioByIdprestatario;
    private Usuario usuarioByIdusuario;
    private Float precio;
    private String estado;
    private String descripcion;
    private Date fechapublicacion;
    private String puntoencuentro;
    private String tiempo;
    private Boolean disponible;
    private Boolean devuelto;
    private Integer calificacion;
    private Set galerias = new HashSet(0);
    private Set comentarios = new HashSet(0);

    public Publicacion() {
        disponible = true;
        devuelto = true;
    }

    public Publicacion(int idpublicacion, Usuario usuarioByIdusuario, String estado, String descripcion, Date fechapublicacion) {
        this.idpublicacion = idpublicacion;
        this.usuarioByIdusuario = usuarioByIdusuario;
        this.estado = estado;
        this.descripcion = descripcion;
        this.fechapublicacion = fechapublicacion;
    }

    public Publicacion(int idpublicacion, Usuario usuarioByIdprestatario, Usuario usuarioByIdusuario, Float precio, String estado, String descripcion, Date fechapublicacion, Integer calificacion, Set galerias, Set comentarios) {
        this.idpublicacion = idpublicacion;
        this.usuarioByIdprestatario = usuarioByIdprestatario;
        this.usuarioByIdusuario = usuarioByIdusuario;
        this.precio = precio;
        this.estado = estado;
        this.descripcion = descripcion;
        this.fechapublicacion = fechapublicacion;
        this.calificacion = calificacion;
        this.galerias = galerias;
        this.comentarios = comentarios;
    }

    @Id
    @Column(name = "idpublicacion", unique = true, nullable = false)
    public int getIdpublicacion() {
        return this.idpublicacion;
    }

    public void setIdpublicacion(int idpublicacion) {
        this.idpublicacion = idpublicacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idprestatario")
    public Usuario getUsuarioByIdprestatario() {
        return this.usuarioByIdprestatario;
    }

    public void setUsuarioByIdprestatario(Usuario usuarioByIdprestatario) {
        this.usuarioByIdprestatario = usuarioByIdprestatario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idusuario", nullable = false)
    public Usuario getUsuarioByIdusuario() {
        return this.usuarioByIdusuario;
    }

    public void setUsuarioByIdusuario(Usuario usuarioByIdusuario) {
        this.usuarioByIdusuario = usuarioByIdusuario;
    }

    @Column(name = "precio", precision = 8, scale = 8)
    public Float getPrecio() {
        return this.precio;
    }

    public void setPrecio(Float precio) {
        this.precio = precio;
    }

    @Column(name = "estado", nullable = false)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "descripcion", nullable = false)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name = "tiempo")
    public String getTiempo() {
        return this.tiempo;
    }

    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }
    
    @Column(name = "puntoencuentro")
    public String getPuntoencuentro() {
        return this.puntoencuentro;
    }

    public void setPuntoencuentro(String puntoencuentro) {
        this.puntoencuentro = puntoencuentro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fechapublicacion", nullable = false, length = 13)
    public Date getFechapublicacion() {
        return this.fechapublicacion;
    }

    public void setFechapublicacion(Date fechapublicacion) {
        this.fechapublicacion = fechapublicacion;
    }

    @Column(name = "calificacion")
    public Integer getCalificacion() {
        return this.calificacion;
    }

    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    
    @Column(name = "disponible")
    public Boolean getDisponible(){
        return this.disponible;
    }
    
    public void setDisponible(Boolean disponible){
        this.disponible = disponible;
    }
    
    @Column(name = "devuelto")
    public Boolean getDevuelto(){
        return this.devuelto;
    }
    
    public void setDevuelto(Boolean devuelto){
        this.devuelto = devuelto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "publicacion")
    public Set getGalerias() {
        return this.galerias;
    }

    public void setGalerias(Set galerias) {
        this.galerias = galerias;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "publicacion")
    public Set getComentarios() {
        return this.comentarios;
    }

    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }

}
